spring.application.name=Notify
spring.datasource.url="endereço DB"
spring.datasource.username="usuario DB"
spring.datasource.password="senha DB"
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

email.username="email remetente"
email.password="senha email remetente"
